import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import JobCategory from "@/components/JobCategory";
export const metadata: Metadata = {
  title: "Seeker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Hero />
        <JobCategory />
        {children}
      </body>
    </html>
  );
}
